### ISSUE TITLE
Symlink subdirectory

### ISSUE THREAD

**Issue by johankj** [thoughtbot/rcm#175]
I was hoping that `SYMLINK_DIRS="dir/subdir"` would create `dir` if it didn't exist and symlink `~/.dir/subdir` to `~/.dotfiles/dir/subdir`, but it looks like it gets ignored and every file in `dir/subdir` gets symlinked as if the `SYMLINK_DIRS` variable was empty.

Is there any way to do this? Or should I just use hooks?

**Comment by mike-burns** [comment]
That should work. Can you provide an example that does not work so that we can better reproduce this bug?

**Comment by johankj** [comment]
Given the following structure
```
.dotfiles/dir
└── subdir
    ├── subsubdir-a
    │   └── file1
    └── subsubdir-b
        ├── file2
        └── file3
```
… and `SYMLINK_DIRS="dir/subdir"`, I would expect the symlink (lsrc) to be:
```
~/.dir/subdir:~/.dotfiles/dir/subdir
```
Instead the following is given:
```
~/.dir/subdir/subsubdir-a/file1:~/.dotfiles/dir/subdir/subsubdir-a/file1
~/.dir/subdir/subsubdir-b/file2:~/.dotfiles/dir/subdir/subsubdir-b/file2
~/.dir/subdir/subsubdir-b/file3:~/.dotfiles/dir/subdir/subsubdir-b/file3
```

In my case, I'd want any future `~/.dir/subdir/subsubdir-x` to be created inside `~/.dotfiles/dir/`.

If I change `SYMLINK_DIRS="dir"` the output is the expected
```
~/.dir:~/.dotfiles/dir
```
… but that is not my preferred setup, as `~/.dir` will contain temporary data which aren't relevant for my dotfiles setup.

**Comment by mike-burns** [comment]
I have looked into this and (re-)learned the issue:

`is_excluded` takes the file in question (without the path) and the `SYMLINK_DIRS` (which includes the path). It then compares them and, since one has the path and the other does not, they do not match. So it considers it not a match.

This works around your immediate problem:

```
SYMLINK_DIRS="subdir"
```

But the larger issue is still there.

**Comment by mike-burns** [comment]
I've made some progress in the `is_excluded-relatively` branch. Hopefully the workaround will suffice for now.

**Comment by willnorris** [comment]
I've run into this issue as well.  

I've been using the workaround, but the main problem with that for me is that it applies to all directories with that name; there's no way to specifically target a given directory.  For example, I just want my `~/.vim/bundle` directory to be a symlink, so I have `SYMLINK_DIRS="bundle"`, but that causes *all* directories named "bundle" to be symlinked.

**Comment by mike-burns** [comment]
Fixed by #192.

**Comment by willnorris** [comment]
@mike-burns unless I'm mistaken, #192 just fixes using globs in excludes (which is great).  It doesn't seem to change anything about symlink dirs, does it?

**Comment by mike-burns** [comment]
To be honest, I do not have a test case for this bug so I do not know for certain that it is fixed. I am basing this on my notes above: the issue is that `is_excluded` does not handle relative file paths. That specific issue is fixed in #192.

I'll re-open this until someone can confirm that it is fixed.

**Comment by willnorris** [comment]
I think #11 was about `is_excluded` not handling relative file paths.  This bug is about `symlink_dirs` similarly not handling relative file paths which this doesn't seem to fix (I tried building from source and experienced the same behavior as before).  I suspect that the logic is similar enough though, that I'll look a little closer at #192 and see if I can modify it for handling `symlink_dirs` as well.

**Comment by ratijas** [comment]
somehow i'm glad i'm not the only one having such problem. :)

today i began managing dotfiles and instantly got hit by this limitation: i'd like to have directory `~/.vimperator/colors` symlinked, while `~/.vimperator` as such contains other sensitive data which must not leak into repository under any circumstances.

unless there's a better solution, i'm symlinking all files under aforementioned `colors` directory. so far, the only drawback in my case is that it makes `lsrc` output _not so great_, but anyways…

thanks for making rcm!

**Comment by mat-m** [comment]
I cannot reproduce on v1.3.3
@ratijas Can you confirm also ?

**Comment by willnorris** [comment]
I have long since restructured my dotfiles where I don't actually run into this anymore.  But I tried to reproduce the original problem I had as best as I could remember, and I can't seem to reproduce it.  So this seems resolved as best as I can tell as well.

**Comment by mike-burns** [comment]
Thank you. Closing.

**Comment by goofrider** [comment]
I know this is already closed but I found a workaround.

I encountered the same problem when try to symlink a directory that's more than 2 levels deep. so:
```
SYMLINK_DIRS="scripts local/bin"
```
works as it should, however:
```
SYMLINK_DIRS="dir1/dir2/dir3"
```
Work symlink the files in dir3. The simple workaround without doing `SYMLINK_DIRS="dir3"` is:
```
SYMLINK_DIRS="dir1/*/dir3"
```

For deeper than 3 levels, use `SYMLINK_DIRS="dir1/dir2/*/dir4"` or `SYMLINK_DIRS="dir1/*/dir4"`. `SYMLINK_DIRS="dir1/*/dir3/dir4"` won't work.

**Comment by willnorris** [comment]
Thanks for sharing the workaround @goofrider!  

Interestingly, I have `SYMLINK_DIRS="config/git/template"` [here](https://github.com/willnorris/dotfiles/blob/b69708cd6462b8f480a9910ad02f9114b726126b/rcrc.example#L3), and it seems to work just fine.  🤷
