### ISSUE TITLE
Ubuntu 17.10 installation failed

### ISSUE THREAD

**Issue by chebykin** [thoughtbot/rcm#221]
It seems that Ubuntu 17.10 support doesn't work out of the box. When I followed instructions from README.md/Ubuntu section the `sudo apt-get update` command failed. I also haven't found the corresponding `artful` folder at http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu/dists/

It can be manually fixed by changing `artful` to `zesty` at `/etc/apt/sources.list.d/martin-frost-ubuntu-thoughtbot-rcm-artful.list` file.

**Comment by IvanAnishchuk** [comment]
Just wanted to create an issue like this :) No, I don't thing it cab be fixed by editing local configs, packages for the the version must be added to ppa first.

We should probably make it a regular event and start pinging @Frost right after the new release is out :D

**Comment by michaelghinrichs** [comment]
seems like this is still an issue, any idea about how much longer we will have to wait? :)

**Comment by Frost** [comment]
HI everyone, and sorry for the delay.

I just uploaded an rcm-1.3.1 package to the ppa. Please test it out and see if it works.

**Comment by michaelghinrichs** [comment]
Wooot! Works for me, thanks so much :)

**Comment by Frost** [comment]
Then I believe this issue can be closed. Ping @mike-burns, maybe?

**Comment by mike-burns** [comment]
Thank you @Frost !
